### ISSUE TITLE
[Feature request] Add VHS filter

### ISSUE THREAD

**Issue by ndbiaw** [Difegue/LCDonald#17]
Rendering the image with SVG makes it look too new to play. I think should add VHS filter to make it look older.

**Comment by Difegue** [comment]
I don't plan on adding filters, but I've added a basic option to darken the game background to make the SVG rendering pop less.  

Another idea was to add a shadow to the SVGs to make them more realistic, but that can't be easily done unless the Avalonia SVG renderer supports transparency.
