### ISSUE TITLE
Tails' Sky Patrol (2003)

### ISSUE THREAD

**Issue by Difegue** [Difegue/LCDonald#2]
![](http://info.sonicretro.org/images/2/27/TailsSkypatrolLCD.jpg)  

- [x] Game owned 
- [x] Manual owned and scanned
- [x] Photos taken (front, back, cover open or closed if there's one)
- [x] LCD elements digitized and vectorized to SVG
- [x] mamelayout file written
- [x] Simulator logic written

**Comment by PW5190** [comment]
The US variant had red buttons instead of blue.

**Comment by Difegue** [comment]
Not a major enough change for me to hunt down a US variant, but maybe someone will provide shots of that eventually :)
