### ISSUE TITLE
Manual for sonic skateboard

### ISSUE THREAD

**Issue by Sam777N** [Difegue/LCDonald#35]
![Picture of the game to simulate]()  

- [ ] Game owned 
- [x] Manual 
![Uploading 1733666845512695578907838999611.jpg…]()
owned and scanned
- [ ] Photos taken (front, back, cover open or closed if there's one)
- [ ] LCD elements digitized and vectorized to SVG
- [ ] mamelayout file written
- [ ] Simulator logic written

**Comment by Difegue** [comment]
👋 Is this for a manual scan? Looks like the picture wasn't uploaded to this issue.

**Comment by Sam777N** [comment]
Yes okay i can upload it again

Pada Sen, 9 Des 2024, 23.51, Difegue ***@***.***> menulis:

**Comment by Sam777N** [comment]
Chinese and English ver.

Pada Sen, 9 Des 2024, 23.51, Difegue ***@***.***> menulis:

**Comment by Sam777N** [comment]
Can you download it?

Pada Sel, 24 Des 2024, 18.16, Samuel Nugraha ***@***.***>
menulis:

**Comment by Difegue** [comment]
no; you might want to consider going through an external file hosting service if uploading to github doesn't work ?

**Comment by Sam777N** [comment]
I already sent it, but why no one can download them?

Pada Rab, 25 Des 2024, 00.05, Samuel Nugraha ***@***.***>
menulis:

**Comment by Sam777N** [comment]
![20241224_175923](https://github.com/user-attachments/assets/cd18df76-cff0-4e17-a0aa-6f7b89d011fc)
![20241224_175851](https://github.com/user-attachments/assets/586956cb-a602-447c-ad66-e580a563a386)
Here

**Comment by Sam777N** [comment]
Okay now download it

**Comment by Sam777N** [comment]
2 pages in one paper

**Comment by Sam777N** [comment]
Merry Christmas

**Comment by Sam777N** [comment]
![Uploading 20241225_003820.jpg…]()
Box

**Comment by Sam777N** [comment]
![Uploading 20241225_003820.jpg…]()

**Comment by Sam777N** [comment]
![Uploading 20241225_003820.jpg…]()

**Comment by Sam777N** [comment]
![Uploading 20241225_003820.jpg…]()

**Comment by Sam777N** [comment]
I try to resize the photos but system cannot read em all

**Comment by Difegue** [comment]
> ![20241224_175923](https://private-user-images.githubusercontent.com/191025041/398455629-cd18df76-cff0-4e17-a0aa-6f7b89d011fc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNDMzNzQsIm5iZiI6MTczNTI0MzA3NCwicGF0aCI6Ii8xOTEwMjUwNDEvMzk4NDU1NjI5LWNkMThkZjc2LWNmZjAtNGUxNy1hMGFhLTZmN2I4OWQwMTFmYy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQxOTU3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWFlNGI3ZjcxN2M1YTgzMmE3ODg5OTU2YzViNjE0NzU5OGQwZDMxNGZmNDY1MGZlMDdlNTE4OWZmYTkxZGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uu94rrJZw15xmJjZUU5HdxdnpJkNg4UghfELM8QleWw) ![20241224_175851](https://private-user-images.githubusercontent.com/191025041/398455647-586956cb-a602-447c-ad66-e580a563a386.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNDMzNzQsIm5iZiI6MTczNTI0MzA3NCwicGF0aCI6Ii8xOTEwMjUwNDEvMzk4NDU1NjQ3LTU4Njk1NmNiLWE2MDItNDQ3Yy1hZDY2LWU1ODBhNTYzYTM4Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQxOTU3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWZiNzAxYmM5OTI4YWJhZDEzZjA5MWI0YjY3NjA2MGVmODJiYTZhMDZkZGEyYjU1ZjlmNjY3MmQyNjNjZGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._BI4m3aybeAuS_tcYSa1qRJ3LA7VbbMGxRQzSHqDOA8) Here

Looks like these uploaded fine -- Thank you very much!
