### ISSUE TITLE
Knuckles' Treasure Hunt (2004)

### ISSUE THREAD

**Issue by Difegue** [Difegue/LCDonald#6]
![Picture of the game to simulate](http://info.sonicretro.org/images/9/9f/Knuckles2005LCD.JPG)  

- [X] Game owned 
- [x] Manual owned and scanned
- [X] Photos taken (front, back, cover open or closed if there's one)
- [x] LCD elements digitized and vectorized to SVG
- [x] mamelayout file written
- [x] Simulator logic written

**Comment by NovaSquirrel** [comment]
The paper is somewhat creased, but I scanned both sides of the instructions, and I can scan at a higher DPI if that'd be better:
![knuckles treasure hunt english](https://user-images.githubusercontent.com/1865623/217401880-8bc54732-ab1e-40fe-9e9c-d2f5ef18e12e.png)
![knuckles treasure hunt spanish](https://user-images.githubusercontent.com/1865623/217401889-1b3a0d06-d3df-410c-9ebf-63c898748915.png)

**Comment by Difegue** [comment]
Thank you very much! I'll include this scan in the repo. 🙏  

A higher DPI version would be much appreciated since it allows me to vectorize some of the character illustrations from the scan, at a much higher fidelity than anything I can get from the games themselves.  

I scanned my manuals at the maximum DPI my scanner can do, but scale them down to 2343x2343 pixels for integration in the repo after vectorizing, if that helps.

**Comment by NovaSquirrel** [comment]
Looks like my scanner goes up to 1200 dpi, so I used that, resulting in scans that are over 3500x3500.
[knuckles 1200dpi.zip](https://github.com/Difegue/LCDonald/files/10689122/knuckles.1200dpi.zip)

Looks like scanning at that high a resolution produces some artifacts, but hopefully it's still helpful.

**Comment by Difegue** [comment]
Wow, thanks for the fast response! I believe I can close this now. 👍  

![image](https://user-images.githubusercontent.com/8237712/217658728-b0997d37-3740-4ada-a7cc-b315a4facfbd.png)
